export const READ_FILE_LOADING = 'READ_FILE_LOADING';
export const READ_FILE_SUCCESS = 'READ_FILE_SUCCESS';
export const READ_FILE_FAILURE = 'READ_FILE_FAILURE';

export const WRITE_FILE_LOADING = 'WRITE_FILE_LOADING';
export const WRITE_FILE_SUCCESS = 'WRITE_FILE_SUCCESS';
export const WRITE_FILE_FAILURE = 'WRITE_FILE_FAILURE';

export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const EDIT_TRANSACTION = 'EDIT_TRANSACTION';

export const FILTER_STATUS = 'FILTER_STATUS';
export const FILTER_TYPE = 'FILTER_TYPE';

export const USER_LOGIN_LOADING = 'USER_LOGIN_LOADING';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const CHANGE_ACTIVE_PAGE = 'CHANGE_ACTIVE_PAGE';
